#!/usr/bin/env bash
# Shared helpers for the Cursor Cloud Agent development environment.
#
# This project normally talks to a hosted Neon (serverless Postgres) database.
# For a self-contained local/Cloud Agent environment we run a plain local
# PostgreSQL instance and put Neon's `wsproxy` in front of it, so the app's
# Neon serverless driver works unchanged (see the localhost branch in
# prisma/db.ts). None of this affects production, where DATABASE_URL points at
# a real Neon host.

set -euo pipefail

PG_VERSION="${PG_VERSION:-16}"
PG_CLUSTER="${PG_CLUSTER:-main}"
DB_NAME="${DB_NAME:-projectrdc}"
DB_USER="${DB_USER:-rdc}"
DB_PASS="${DB_PASS:-rdc}"
WSPROXY_PORT="${WSPROXY_PORT:-5433}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

log() { printf '\n\033[1;34m[cloud-agent]\033[0m %s\n' "$*"; }

# Pinned Neon wsproxy version (matches what the environment was validated with).
WSPROXY_REF="${WSPROXY_REF:-github.com/neondatabase/wsproxy@v0.0.0-20241104134926-99ed92dd75ba}"

# Install system dependencies (PostgreSQL + Neon wsproxy) if they are missing.
# Idempotent: on a snapshot/base image that already has them, this is a no-op.
ensure_system_deps() {
  if ! command -v pg_lsclusters >/dev/null 2>&1; then
    log "Installing PostgreSQL ${PG_VERSION}..."
    sudo apt-get update -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib
  fi

  if ! command -v wsproxy >/dev/null 2>&1; then
    log "Building Neon wsproxy (${WSPROXY_REF})..."
    if ! command -v go >/dev/null 2>&1; then
      sudo apt-get update -y
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y golang-go
    fi
    GOBIN=/tmp/gobin GOFLAGS=-mod=mod go install "${WSPROXY_REF}"
    sudo install -m 0755 /tmp/gobin/wsproxy /usr/local/bin/wsproxy
  fi
}

# Start the local PostgreSQL cluster if it is not already online. Idempotent.
ensure_postgres() {
  if sudo pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q '^online$'; then
    log "PostgreSQL ${PG_VERSION}/${PG_CLUSTER} already online."
  else
    log "Starting PostgreSQL ${PG_VERSION}/${PG_CLUSTER}..."
    sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start
  fi
  # Wait for the socket to accept connections.
  for _ in $(seq 1 30); do
    if sudo -u postgres pg_isready -q; then return 0; fi
    sleep 1
  done
  log "PostgreSQL did not become ready in time." >&2
  return 1
}

# Create the application role and database if they do not exist. Idempotent.
ensure_role_db() {
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
    log "Creating role ${DB_USER}."
    sudo -u postgres psql -c "CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASS}' SUPERUSER;"
  fi
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
    log "Creating database ${DB_NAME}."
    sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"
  fi
}

# Write the local .env files if they are missing. Does not overwrite user edits.
write_env_files() {
  local db_url="postgres://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"
  local direct_url="postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"

  if [ ! -f "${REPO_ROOT}/.env" ]; then
    log "Writing .env"
    cat >"${REPO_ROOT}/.env" <<EOF
# Auto-generated by scripts/cloud-agent for local development.
DATABASE_URL="${db_url}"
DIRECT_URL="${direct_url}"
NEXT_PUBLIC_POSTHOG_KEY="phc_local_dev_placeholder"
NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
RESEND_API_KEY="re_local_dev_placeholder"
AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"
BETTER_AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"
EOF
  fi

  if [ ! -f "${REPO_ROOT}/.env.development.local" ]; then
    log "Writing .env.development.local"
    cat >"${REPO_ROOT}/.env.development.local" <<EOF
# Auto-generated by scripts/cloud-agent for local development (npm run dev).
DATABASE_URL="${db_url}"
DIRECT_URL="${direct_url}"
AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"
BETTER_AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"
AUTH_TRUST_HOST="true"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NEXT_PUBLIC_POSTHOG_KEY="phc_local_dev_placeholder"
NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
RESEND_API_KEY="re_local_dev_placeholder"
EOF
  fi

  # The seed reads an optional production export; provide an empty list so a
  # fresh database seeds members + games cleanly without it.
  if [ ! -f "${REPO_ROOT}/sessions_backup.json" ]; then
    log "Writing empty sessions_backup.json"
    echo "[]" >"${REPO_ROOT}/sessions_backup.json"
  fi
}

# Start Neon wsproxy on WSPROXY_PORT if it is not already listening. Idempotent.
ensure_wsproxy() {
  if (exec 3<>"/dev/tcp/127.0.0.1/${WSPROXY_PORT}") 2>/dev/null; then
    exec 3>&- 3<&- 2>/dev/null || true
    log "wsproxy already listening on :${WSPROXY_PORT}."
    return 0
  fi
  log "Starting wsproxy on :${WSPROXY_PORT}..."
  LISTEN_PORT=":${WSPROXY_PORT}" ALLOW_ADDR_REGEX=".*" \
    APPEND_PORT="localhost:5432" LOG_TRAFFIC="false" \
    nohup wsproxy >/tmp/wsproxy.log 2>&1 &
  for _ in $(seq 1 15); do
    if (exec 3<>"/dev/tcp/127.0.0.1/${WSPROXY_PORT}") 2>/dev/null; then
      exec 3>&- 3<&- 2>/dev/null || true
      return 0
    fi
    sleep 1
  done
  log "wsproxy did not start in time." >&2
  return 1
}
