#!/usr/bin/env bash
# Shared helpers for the Cursor Cloud Agent development environment.
#
# Local Postgres sits behind a Neon-compatible TLS proxy on :443
# (`neon-local-proxy.mjs`) so @neondatabase/serverless works unchanged.
# DATABASE_URL uses db.localtest.me, not localhost.

set -euo pipefail

PG_VERSION="${PG_VERSION:-}"
DB_NAME="${DB_NAME:-projectrdc}"
DB_USER="${DB_USER:-rdc}"
DB_PASS="${DB_PASS:-rdc}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEV_DIR="$REPO_ROOT/.cursor/dev"
CERT_DIR="$DEV_DIR/certs"

log() { printf '\n\033[1;34m[cloud-agent]\033[0m %s\n' "$*"; }

db_url() {
  printf 'postgresql://%s:%s@db.localtest.me:5432/%s?sslmode=disable' \
    "$DB_USER" "$DB_PASS" "$DB_NAME"
}

ensure_hosts() {
  for h in db.localtest.me api.localtest.me apiauth.localtest.me; do
    grep -qE "^127\.0\.0\.1[[:space:]]+$h(\$|[[:space:]])" /etc/hosts || \
      echo "127.0.0.1 $h" | sudo tee -a /etc/hosts >/dev/null
  done
}

ensure_postgres() {
  if ! command -v pg_ctlcluster >/dev/null 2>&1; then
    sudo apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update -qq
    sudo DEBIAN_FRONTEND=noninteractive apt-get \
      -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false \
      install -y -qq postgresql postgresql-contrib
  fi
  PG_VERSION="$(ls /etc/postgresql 2>/dev/null | sort -n | tail -1)"
  if [ -z "$PG_VERSION" ]; then
    echo "Could not detect a PostgreSQL cluster under /etc/postgresql" >&2
    exit 1
  fi
  HBA="/etc/postgresql/$PG_VERSION/main/pg_hba.conf"
  sudo sed -i -E 's#^(host[[:space:]]+all[[:space:]]+all[[:space:]]+127\.0\.0\.1/32[[:space:]]+).*#\1password#' "$HBA"
  sudo sed -i -E 's#^(host[[:space:]]+all[[:space:]]+all[[:space:]]+::1/128[[:space:]]+).*#\1password#' "$HBA"
  sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
  for _ in $(seq 1 30); do
    if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
    sleep 1
  done
  sudo pg_ctlcluster "$PG_VERSION" main reload 2>/dev/null || true
}

ensure_role_db() {
  sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' SUPERUSER;
  END IF;
END \$\$;
SQL
  sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
    sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
}

ensure_certs() {
  if [ -f "$CERT_DIR/ca.crt" ] && [ -f "$CERT_DIR/server.crt" ]; then
    return 0
  fi
  mkdir -p "$CERT_DIR"
  (
    cd "$CERT_DIR"
    openssl genrsa -out ca.key 2048 2>/dev/null
    openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 \
      -subj "/CN=Local Dev CA" -out ca.crt 2>/dev/null
    openssl genrsa -out server.key 2048 2>/dev/null
    openssl req -new -key server.key -subj "/CN=db.localtest.me" -out server.csr 2>/dev/null
    cat > server.ext <<'EXT'
subjectAltName = DNS:db.localtest.me, DNS:api.localtest.me, DNS:apiauth.localtest.me, DNS:localhost, IP:127.0.0.1
EXT
    openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
      -out server.crt -days 3650 -sha256 -extfile server.ext 2>/dev/null
  )
}

write_env_files() {
  local url
  url="$(db_url)"
  if [ ! -f "$REPO_ROOT/.env" ]; then
    cat >"$REPO_ROOT/.env" <<EOF
# Auto-generated by .cursor/dev for local Cloud Agent development.
DATABASE_URL="${url}"
DIRECT_URL="${url}"
BETTER_AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"
TEST_AUTH_SECRET="local-test-auth-secret-not-for-production"
NEXT_PUBLIC_POSTHOG_KEY="phc_local_dev_placeholder"
NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
RESEND_API_KEY="re_local_dev_placeholder"
EOF
  else
    grep -q '^TEST_AUTH_SECRET=' "$REPO_ROOT/.env" || \
      printf '\nTEST_AUTH_SECRET="local-test-auth-secret-not-for-production"\n' >>"$REPO_ROOT/.env"
    grep -q '^BETTER_AUTH_SECRET=' "$REPO_ROOT/.env" || \
      printf '\nBETTER_AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"\n' >>"$REPO_ROOT/.env"
  fi

  if [ ! -f "$REPO_ROOT/.env.development.local" ]; then
    cat >"$REPO_ROOT/.env.development.local" <<EOF
DATABASE_URL="${url}"
DIRECT_URL="${url}"
BETTER_AUTH_SECRET="local-dev-secret-not-for-production-0123456789abcdef"
BETTER_AUTH_URL="http://localhost:3000"
TEST_AUTH_SECRET="local-test-auth-secret-not-for-production"
NEXT_PUBLIC_POSTHOG_KEY="phc_local_dev_placeholder"
NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
RESEND_API_KEY="re_local_dev_placeholder"
EOF
  fi

  if [ ! -f "$REPO_ROOT/sessions_backup.json" ]; then
    echo "[]" >"$REPO_ROOT/sessions_backup.json"
  fi
}

start_proxy_for_seed() {
  sudo sysctl -w net.ipv4.ip_unprivileged_port_start=443 >/dev/null
  node "$DEV_DIR/neon-local-proxy.mjs" >/tmp/neon-proxy-seed.log 2>&1 &
  PROXY_PID=$!
  PROXY_OK=0
  for _ in $(seq 1 20); do
    if curl -sf --cacert "$CERT_DIR/ca.crt" https://db.localtest.me/health >/dev/null 2>&1; then
      PROXY_OK=1
      break
    fi
    sleep 0.5
  done
  if [ "$PROXY_OK" != 1 ]; then
    echo "Neon local proxy did not become healthy on :443. Last log:" >&2
    cat /tmp/neon-proxy-seed.log >&2 || true
    kill "$PROXY_PID" 2>/dev/null || true
    exit 1
  fi
}
